**Pasos iniciales**

In [ ]:
# pip install numpy
import numpy as np

**Aspectos básicos**

In [ ]:
# Creación de arrays
a = np.array([[2, 6, 1],[7, 7, 7],[8, 4, 5]], dtype='int32') # Cada byte tiene 8 bits
print(a)

# Obtener número de dimensiones
print("La dimensión es:", a.ndim)

# Obtener el orden
print("El orden o forma es:", a.shape)

# Obtener tipo de dato
print("El tipo de dato es:", a.dtype)

# Obtener la cantidad de datos
print("La cantidad de datos es:", a.size)

# Obtener tamaño en bytes
print("El número de bytes por celda es:", a.itemsize)
print("El número total de bytes es:", a.nbytes)


[[2 6 1]
 [7 7 7]
 [8 4 5]]
La dimensión es: 2
El orden o forma es: (3, 3)
El tipo de dato es: int32
La cantidad de datos es: 9
El número de bytes por celda es: 4
El número total de bytes es: 36


**Lectura/escritura de elementos, filas o columnas**

In [ ]:
b = np.array([[2, 5, 3, 9, 8],[7, 3, 4, 2, 8],[1, 3, 1, 0, 6]])
print(b)

# Lectura de elemento
print(b[1,2])

# Lectura de una columna
# Sintaxis de indexado ==> arreglo[fila,columna] ==> [fila or columna](startindex:endindex)
print(b[:,-1])
print(b[:,2])

# Lectura de una fila
print(b[0,:])
print(b[-1,:])

# Lectura más específica
print(b[0:2,:-1])
print(b[1:,2:])

# Reemplazar datos
b[0,:] = 0
b[:,-1] = 0
print(b)

[[2 5 3 9 8]
 [7 3 4 2 8]
 [1 3 1 0 6]]
4
[8 8 6]
[3 4 1]
[2 5 3 9 8]
[1 3 1 0 6]
[[2 5 3 9]
 [7 3 4 2]]
[[4 2 8]
 [1 0 6]]
[[0 0 0 0 0]
 [7 3 4 2 0]
 [1 3 1 0 0]]


**Arrays predeterminados de NumPy**

In [ ]:
# Array lleno de ceros
ceros = np.zeros((5,5), dtype='int32')
print(ceros)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
# Array lleno de unos
unos = np.ones((4, 6), dtype='int32')
print(unos)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [ ]:
# Array lleno de cualquier número
lleno = np.full((3, 7), 10)
print(lleno)

[[10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10]]


In [ ]:
# Arreglo lleno importando shape
lleno_copia = np.full_like(unos, 9)
print(lleno_copia)

[[9 9 9 9 9 9]
 [9 9 9 9 9 9]
 [9 9 9 9 9 9]
 [9 9 9 9 9 9]]


In [ ]:
# Arreglo lleno de números random entre cero y uno
aleatorio = np.random.rand(5, 5)
print(aleatorio)

[[0.9141445  0.85273543 0.89357268 0.41214115 0.02288837]
 [0.00740095 0.89220601 0.32747607 0.486561   0.91544952]
 [0.18123468 0.12902853 0.79248056 0.88995881 0.42155279]
 [0.31957657 0.50237629 0.27169672 0.5727382  0.57544341]
 [0.88049449 0.91055181 0.07882567 0.46491708 0.93609989]]


In [ ]:
# Arreglo lleno de números random entre un rango
aleatorio_rango = np.random.randint(50, 100, size=(3, 3))
print(aleatorio_rango)

[[88 60 96]
 [69 79 58]
 [88 80 70]]


In [ ]:
# Arreglo identidad
identidad = np.identity(5, dtype='int32')
print(identidad)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
# Arreglo ojo
ojo = np.eye(5, 10, -1, dtype='int32')
print(ojo)

[[0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]]


In [ ]:
# Arreglos repetidos
repetido = np.repeat(aleatorio_rango, 3, axis=1)
print(repetido)

[[88 88 88 60 60 60 96 96 96]
 [69 69 69 79 79 79 58 58 58]
 [88 88 88 80 80 80 70 70 70]]


In [ ]:
# EJEMPLO DE ESTE TEMA
# Ejemplo 1
matriz_1 = np.full((6,6), 8)
matriz_1[0:2,0:3] = 2
matriz_1[-2:,-3:] = 4

print(matriz_1)

#----------------------------
# Ejemplo 2
matriz_2a = np.zeros((4,3)) 
matriz_2a[1:3,1] = 2
matriz_2b = np.ones((4,3))
matriz_2b[1:3,1] = 5

matriz_2 = np.hstack((matriz_2a, matriz_2b))

print(matriz_2)

#----------------------------
# Ejemplo 3
matriz_3a = np.full((6,2),3)
matriz_3b = np.full((2,4),7)
matriz_3c = np.identity(4)

matriz_3 = np.hstack((matriz_3a, np.vstack((matriz_3c,matriz_3b))))

print(matriz_3)


[[2 2 2 8 8 8]
 [2 2 2 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 4 4 4]
 [8 8 8 4 4 4]]
[[0. 0. 0. 1. 1. 1.]
 [0. 2. 0. 1. 5. 1.]
 [0. 2. 0. 1. 5. 1.]
 [0. 0. 0. 1. 1. 1.]]
[[3. 3. 1. 0. 0. 0.]
 [3. 3. 0. 1. 0. 0.]
 [3. 3. 0. 0. 1. 0.]
 [3. 3. 0. 0. 0. 1.]
 [3. 3. 7. 7. 7. 7.]
 [3. 3. 7. 7. 7. 7.]]


**Operaciones aritméticas básicas**

In [ ]:
operacion = np.array([[0, 1, 3],[5, 2, 6],[9, 4, 7]])
print(operacion)

# Suma
print(operacion + 2)
# Resta
print(operacion - 2)
# Multiplicar
print(operacion * 2)
# Dividir
print(operacion / 2)
# Potencia
print(pow(operacion, 2))
# Raiz
print(np.sqrt(operacion))
# Seno
print(np.sin(operacion))


[[0 1 3]
 [5 2 6]
 [9 4 7]]
[[ 2  3  5]
 [ 7  4  8]
 [11  6  9]]
[[-2 -1  1]
 [ 3  0  4]
 [ 7  2  5]]
[[ 0  2  6]
 [10  4 12]
 [18  8 14]]
[[0.  0.5 1.5]
 [2.5 1.  3. ]
 [4.5 2.  3.5]]
[[ 0  1  9]
 [25  4 36]
 [81 16 49]]
[[0.         1.         1.73205081]
 [2.23606798 1.41421356 2.44948974]
 [3.         2.         2.64575131]]
[[ 0.          0.84147098  0.14112001]
 [-0.95892427  0.90929743 -0.2794155 ]
 [ 0.41211849 -0.7568025   0.6569866 ]]


**Operaciones de Álgebra Lineal**

In [ ]:
algebra = np.array([[1, 2],[5, 0],[9, 8]])
print(algebra, algebra.shape)

vector_1 = np.array([1, 2, 3])
vector_2 = np.array([4, -1, 9])

# Multiplicación de matrices
print(np.matmul(operacion, algebra))
# Hallar determinante
print(np.linalg.det(operacion))
# Hallar inversa
print(np.linalg.inv(operacion))
# Hallar eigenvalores
print(np.linalg.eigvals(operacion)) 
# Hallar el producto punto o producto cruz de vectores
print(np.dot(vector_1, vector_2))
print(np.cross(vector_1, vector_2))

[[1 2]
 [5 0]
 [9 8]] (3, 2)
[[32 24]
 [69 58]
 [92 74]]
25.000000000000007
[[-0.4   0.2   0.  ]
 [ 0.76 -1.08  0.6 ]
 [ 0.08  0.36 -0.2 ]]
[12.5154557  -2.80275276 -0.71270294]
29
[21  3 -9]


**Operaciones básicas de estadística**

In [ ]:
estadistica = np.array([[1, 2, 8, 10, 3, 6, 2],[11, 14, 7, 12, 11, 10, 9],[0, -1, 5, 7, 2, 1, -1]])
print(estadistica)

# Hallar máximos y mínimos en general
print(np.min(estadistica))
print(np.max(estadistica))

# Hallar máximos y mínimos por columna, fila,...
print(np.min(estadistica, axis=1))
print(np.max(estadistica, axis=0))

# Hallar promedios
print(np.average(estadistica, axis=1))

# Hallar suma
print(np.sum(estadistica, axis=0))

# Hallar el producto
print(np.prod(estadistica, axis=1))

# Hallar el mediana 
print(np.median(estadistica))

# Hallar la desviación estándar
print(np.std(estadistica))


[[ 1  2  8 10  3  6  2]
 [11 14  7 12 11 10  9]
 [ 0 -1  5  7  2  1 -1]]
-1
14
[ 1  7 -1]
[11 14  8 12 11 10  9]
[ 4.57142857 10.57142857  1.85714286]
[12 15 20 29 16 17 10]
[    5760 12806640        0]
6.0
4.560005569475853


**Reorganizar arrays**

In [ ]:
# PARA VER HSTACK Y VSTACK VER EJEMPLO DEL TEMA DE ARRAYS PREDETERMINADOS

# Reshape

reforma = np.array([[6, 5, 4, 3, 2, 1],[1, 2, 3, 4, 5, 6],[7, 8, 9, 0, 1, 2],[6, 7, 8, 9, 3, 4]])
print(reforma, reforma.size)

print(np.reshape(reforma, (3, 8)))

[[6 5 4 3 2 1]
 [1 2 3 4 5 6]
 [7 8 9 0 1 2]
 [6 7 8 9 3 4]] 24
[[6 5 4 3 2 1 1 2]
 [3 4 5 6 7 8 9 0]
 [1 2 6 7 8 9 3 4]]


**Leer datos externos**

In [ ]:
edades = np.genfromtxt('edades.txt', delimiter=',', dtype='int32')
print(edades)

print(np.average(edades))

[[ 45  32  78  12   1  34   2]
 [ 54  32  34  45  23  84  91]
 [ 34 100  43  12  14  28  51]
 [ 69  38  76  50  78   2   7]]
41.75


**Indexado avanzado y máscaras booleanas**

In [ ]:
# Matrices y máscaras booleanas
promedio = np.average(edades)
edad_joven = 30
edad_adultez = 18
print("Promedio:", promedio)
mascara_1 = edades > promedio
mascara_2 = edades <= edad_joven

print(edades[mascara_2])

# Any == OR
print(np.any(edades <= edad_adultez, axis=0))

# All = AND
mascara_3 = np.all(edades >= edad_joven, axis=0)
print(edades[:,mascara_3])

# Indexado con listas
print(edades[[0,1,2],[2,3,4]])

Promedio: 41.75
[12  1  2 23 12 14 28  2  7]
[False False False  True  True  True  True]
[[ 45  32  78]
 [ 54  32  34]
 [ 34 100  43]
 [ 69  38  76]]
[78 45 14]


In [ ]:
# EJEMPLOS DEL TEMA 9

#Ejemplo 1
c = np.full((6,6), 2)
d = np.eye(6, 6, dtype='bool')
e = np.eye(6, 6, 3, dtype='bool')
f = np.eye(6, 6, -3, dtype='bool')

c[d | e | f] = 1

print(c)

#Ejemplo 2
c = np.full((4,4), 4)
d = np.eye(4, 4, dtype='bool')

c[d] = 9

print(np.hstack((c, np.ones((4,2)))))

#Ejemplo 3
c = np.zeros((6,6))

lista_ref = [8, 9, 5, 3, 1, 0, 2, 4, 5, 6, 9]
#            0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
#            -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5

for i in range(-5, 6):
  mascara = np.eye(6, 6, i, dtype='bool')
  c[mascara] = lista_ref[i + 5]

print(c)

# Ejemplo 4
res = (c[:,[1,3,4]])[[0,1,-1,-2],:]
print(res)


[[1 2 2 1 2 2]
 [2 1 2 2 1 2]
 [2 2 1 2 2 1]
 [1 2 2 1 2 2]
 [2 1 2 2 1 2]
 [2 2 1 2 2 1]]
[[9. 4. 4. 4. 1. 1.]
 [4. 9. 4. 4. 1. 1.]
 [4. 4. 9. 4. 1. 1.]
 [4. 4. 4. 9. 1. 1.]]
[[0. 2. 4. 5. 6. 9.]
 [1. 0. 2. 4. 5. 6.]
 [3. 1. 0. 2. 4. 5.]
 [5. 3. 1. 0. 2. 4.]
 [9. 5. 3. 1. 0. 2.]
 [8. 9. 5. 3. 1. 0.]]
[[2. 5. 6.]
 [0. 4. 5.]
 [9. 3. 1.]
 [5. 1. 0.]]


**Misceláneo**

In [1]:
# OJO al copiar arrays, se debe usar ".copy()"
m_a = np.array([[1, 2, 3],[4, 5, 6]])
m_b = m_a.copy()

NameError: ignored